build:
  image: golang:1.7.1
  commands:
    - go version
    - go get github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.11.1 && go install && cd -
    - glide install
    - go test -v $(go list ./... | grep -v /vendor/)
