
# Gopkg.toml
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/equinox-io/equinox"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/errwrap"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/henvic/uilive"

[[constraint]]
  branch = "fix-windows-subsystem"
  name = "github.com/henvic/browser"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/wedeploy/wedeploy-sdk-go"
  version = "2.1.1"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "=1.33.0"

[[constraint]]
  name = "github.com/henvic/socketio"
  version = "0.0.3-beta"
