#! /usr/bin/expect

spawn $env(SHELL)

#####################################################
Scenario: "Cannot delete without signing in"
#####################################################

logout $_tester(email)

while {1} {
  send "we delete\r"
  expect {
    timeout { handle_timeout; break }
    "You need to log in before using \"we delete\"."
  }
  expect {
    timeout { handle_timeout; break }
    "Open your browser and authenticate?"
  }
  send "n\r"
  expect {
    timeout { handle_timeout; break }
    "Login canceled."
  }
  break
}

#####################################################
Scenario: "Delete a project"
#####################################################

login $_tester(email) $_tester(pw)

create_project delete1

while {1} {
  send "we delete\r"
  expect {
    timeout { handle_timeout; break }
    "Please*select*a project or a service"
  }
  expect {
    timeout { handle_timeout; break }
    "Type project/service ID or service #"
  }
  send "delete1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Enter the project ID*delete1*to delete it permanently"
  }
  send "delete1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Deleting project*delete1"
  }
  send "we curl /projects/delete1\r"
  expect {
    timeout { handle_timeout; break }
    "Project does not exist."
  }
  break
}

#####################################################
Scenario: "Delete a service"
#####################################################

create_project delete2
create_service delete2 hosting1
create_service delete2 hosting2

while {1} {
  send "we delete\r"
  expect {
    timeout { handle_timeout; break }
    "Please*select*a project or a service"
  }
  expect {
    timeout { handle_timeout; break }
    "Type project/service ID or service #"
  }
  send "hosting1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Enter the service ID*hosting1*to delete it permanently"
  }
  send "hosting1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Deleting service*hosting1*on project*delete2"
  }
  send "we curl /projects/delete2/services/hosting1\r"
  expect {
    timeout { handle_timeout; break }
    "Service delete2/hosting1 does not exist."
  }
  verify_service_exists delete2 hosting2
  break
}

delete_project delete2

#####################################################
Scenario: "Delete a project with -p flag"
#####################################################

create_project delete3
create_project delete4

while {1} {
  send "we delete -p delete4\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Enter the project ID*delete4*to delete it permanently"
  }
  send "delete4\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Deleting project*delete4"
  }
  send "we curl /projects/delete4\r"
  expect {
    timeout { handle_timeout; break }
    "Project does not exist."
  }
  send "we curl /projects/delete3\r"
  expect {
    timeout { handle_timeout; break }
    -gl "\"projectId\"*: *\"delete3\""
  }
  break
}

delete_project delete3

#####################################################
Scenario: "Delete a service with -p and -s flags"
#####################################################

create_project delete5
create_service delete5 hosting1
create_service delete5 hosting2

while {1} {
  send "we delete -p delete5 -s hosting1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Enter the service ID*hosting1*to delete it permanently"
  }
  send "hosting1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Deleting service*hosting1*on project*delete5"
  }
  send "we curl /projects/delete5/services/hosting1\r"
  expect {
    timeout { handle_timeout; break }
    "Service delete5/hosting1 does not exist."
  }
  verify_service_exists delete5 hosting2
  break
}

delete_project delete5

#####################################################
Scenario: "Delete a project with -e flag"
#####################################################

create_project delete6
create_project delete6-uat true

while {1} {
  send "we delete -p delete6 -e uat\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Enter the project ID*delete6-uat*to delete it permanently"
  }
  send "delete6-uat\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Deleting project*delete6-uat"
  }
  send "we curl /projects/delete6-uat\r"
  expect {
    timeout { handle_timeout; break }
    "Project does not exist."
  }
  send "we curl /projects/delete6\r"
  expect {
    timeout { handle_timeout; break }
    -gl "\"projectId\"*: *\"delete6\""
  }
  break
}

delete_project delete6

#####################################################
Scenario: "Delete a service with -e flag"
#####################################################

create_project delete7
create_project delete7-dev true
create_service delete7 hosting1
create_service delete7-dev hosting2

while {1} {
  send "we delete -p delete7 -e dev -s hosting2\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Enter the service ID*hosting2*to delete it permanently"
  }
  send "hosting2\r"
  expect {
    timeout { handle_timeout; break }
    -gl "Deleting service*hosting2*on project*delete7-dev"
  }
  send "we curl /projects/delete7-dev/services/hosting2\r"
  expect {
    timeout { handle_timeout; break }
    "Service delete7-dev/hosting2 does not exist."
  }
  verify_service_exists delete7 hosting1
  break
}

delete_project delete7
