#! /usr/bin/expect

source ../procs/curl_procs.tcl
source ../procs/shared_procs.tcl

# if env(TESTER_EMAIL) has a value, assume tester already exists
# otherwise, default tester needs to be created
if { ![info exists ::env(TESTER_EMAIL)] } {
  print_msg "TESTER_EMAIL: $_tester(email)"
  create_user $_tester(email)
} else {
  print_msg "TESTER_EMAIL: $::env(TESTER_EMAIL)"
}

# initialize test report file
set report_file [open $_test_report w]
close $report_file

# list of test files to run
set test_files {
  login.exp \
  list.exp \
  deploy.exp \
  log.exp \
  restart.exp \
  new.exp \
  delete.exp
}

# run tests
foreach {test_file} $test_files {
  source $test_file
}

print_msg "All done running tests!" green
