package main

import (
	"bytes"
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"
)

func main() {
	buf := &bytes.Buffer{}
	cmd := exec.CommandContext(context.Background(), "vendorlicenses")
	cmd.Dir = ".."
	cmd.Stderr = os.Stderr
	cmd.Stdout = buf
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "%+v\n", err)
	}

	var s = buf.String()
	s = strings.Replace(fmt.Sprintf("%q", s), "\\n", "\n", -1)
	s = strings.Replace(s, `\"`, `"`, -1)
	s = strings.Replace(s, "`", "` + \"`\" + `", -1)
	s = "`" + s[1:len(s)-1] + "`"

	var text = fmt.Sprintf(`// Code generated by legal generator; DO NOT EDIT.

package legal

// Licenses (legal notices)
var Licenses = %s
`, s)

	var err = ioutil.WriteFile("licenses.go", []byte(text), 0644)

	if err != nil {
		fmt.Fprintf(os.Stderr, "%+v", err)
		os.Exit(1)
	}
}
