package main

import (
	"fmt"

	"github.com/wedeploy/cli/update/releasenotes"
)

var header = `---
<!--
This file is autogenerated, do not edit; changes may be undone by the next 'wedeploy/cli: make release-notes-page'.
-->
title: "CLI Updates"
description: "Check out the latest releases of the WeDeploy CLI"
layout: "updates"
updates:
`

var entryTemplate = ` -
  version: %v
  date: %v
  description: %v
`

func main() {
	fmt.Print(header)

	for nc := len(releasenotes.ReleaseNotes) - 1; nc >= 0; nc-- {
		note := releasenotes.ReleaseNotes[nc]
		fmt.Printf(entryTemplate, note.Version, note.Date, note.Description)
	}

	fmt.Println("---")
}
