#!/usr/bin/expect

spawn $env(SHELL)

Feature: "Domain"

Scenario: "Add and delete a custom domain" {
  set domain1 [prefixed_project domain1]
  set domain qadomain1.$::service_domain

  create_project $domain1
  create_service $domain1 hosting1

  send "$::bin domain show\r"
  expect {
    timeout { handle_timeout; break }
    "Please*select*a service from the list below."
  }
  send "1\r"
  expect {
    timeout { handle_timeout; break }
    "No custom domains found."
  }
  send "$::bin domain add $domain\r"
  expect {
    timeout { handle_timeout; break }
    "Type service ID or #"
  }
  send "hosting1\r"
  expect {
    timeout { handle_timeout; break }
    "Custom domain \"$domain\" added."
  }
  send "$::bin domain show -p $domain1 -s hosting1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "1*$domain"
  }
  send "$::bin curl /projects/$domain1/services/hosting1\r"
  expect {
    timeout { handle_timeout; break }
    -gl "\"customDomains\"*:*\[*\"qadomain1.wedeploy.*\""
  }
  send "$::bin domain delete -p $domain1 -s hosting1\r"
  expect {
    timeout { handle_timeout; break }
    "Select a custom domain # or address to delete"
  }
  send "$domain\r"
  expect {
    timeout { handle_timeout; break }
    "Custom domain \"$domain\" deleted."
  }
  send "$::bin domain show -p $domain1 -s hosting1\r"
  expect {
    timeout {}
    $domain {
      expectation_not_met "Should not have custom domain $domain"
      break
    }
  }
  send "$::bin curl /projects/$domain1/services/hosting1\r"
  expect {
    timeout {}
    $domain {
      expectation_not_met "Should not have custom domain $domain"
      break
    }
  }
} { delete_project $domain1 }
