#!/usr/bin/expect

spawn $env(SHELL)

Feature: "List"

Scenario: "List with no projects" {
  send "$::bin list\r"
  expect {
    timeout { handle_timeout }
    "No project found."
  }
}

Scenario: "List project with no services" {
  set list1 [prefixed_project list1]
  create_project "$list1"

  send "$::bin list\r"
  expect {
    timeout { handle_timeout }
    "$list1*zero services deployed"
  }
} { delete_project "$list1" }

Scenario: "List project and services" {
  set list2 [prefixed_project list2]
  create_project "$list2"
  create_service "$list2" "hosting1"
  create_service "$list2" "hosting2"

  send "$::bin list\r"
  expect {
    timeout {handle_timeout}
    -re "list2.*hosting1-$list2\.$::_service_domain.*wedeploy/hosting.*none\
        .*list2.*hosting2-$list2\.$::_service_domain.*wedeploy/hosting.*none"
  }
} { delete_project "$list2" }
