#! /usr/bin/expect

spawn $env(SHELL)

Feature: "Login"

Scenario: "Login without browser" {
  logout $::_tester(email)

  send "we login --no-browser\r"
  expect {
    timeout { handle_timeout; break }
    "Your email:"
  }
  send "$::_tester(email)\r"
  expect {
    timeout { handle_timeout; break }
    "Now, your password:"
  }
  send "$::_tester(pw)\r"
  expect {
    timeout { handle_timeout; break }
    "Type a command and press Enter to execute it."
  }
}
