#!/usr/bin/expect

logout $::_tester(email)

Feature: "Login"

Scenario: "Login without browser" {
  spawn $::bin login --no-browser
  expect {
    timeout { handle_timeout; break }
    "Your email:"
  }
  send "$::_tester(email)\r"
  expect {
    timeout { handle_timeout; break }
    "Now, your password:"
  }
  send "$::_tester(password)\r"
  expect {
    timeout { handle_timeout; break }
    "Type a command and press Enter to execute it."
  }
}

# TODO(henvic): write test case logging in with token
