#!/usr/bin/expect

send_user "\n\nVerifying if not logged in precondition is met.\n"
spawn $::bin inspect token
expect {
  timeout {
    print_msg_stderr "\nTimed out checking if the user is not logged in.\n"
    exit 1
  }
  eof {
    print_msg_stderr "\nRefusing to run tests using an already logged-in user.\n"
    exit 1
  }
  "User is not logged in."
}

login $::_tester(email) $::_tester(password)

send_user "\n\nVerifying if no projects found precondition is met.\n"
spawn $::bin list
expect {
  timeout {
    print_msg_stderr "\nTimed out.\n"
    exit 1
  }
  eof {
    print_msg_stderr "\nRefusing to run tests because projects already exists. Explicit cleanup is required to continue.\n"
    print_msg_stderr "Run \"make cleanup-functional-tests-environment\" to clean up any leftovers from previous functional tests runs."
    print_msg_stderr "For safety, only tests created by the functional tests are cleaned up in this process. Manual cleanup is required for anything else."
    exit 1
  }
  "No project found."
}
